<?php

namespace ccxt;

// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

use Exception; // a common import
use ccxt\abstract\bitbay as VersoriumX;

class bitbay extends VersoriumX {

    public function describe() {
        return $this->deep_extend(parent::describe(), array(
            'id' => 'bitbay',
            'name' => 'BitBay',
            'alias' => true,
        ));
    }
}
